version: '3.1' 

services:
  bot:
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    image: bot:v1_0_0
    volumes:
      - config-volume:/opt/app/config

volumes:
  config-volume:
    driver: local
    driver_opts:
      type: none
      device: '/Users/a17540258/IdeaProjects/bot/docker'
      o: bind

