version: '3.1' 

services:
  bot:
    restart: always
    image: saleksandrov/lugabot-repo:latest
    environment:
      WEATHER_TOKEN: VALUE
      KEYSTORE_PASSWORD: VALUE
      KEYSTORE_PATH: /opt/app/jks/bot_long.jks
    volumes:
      - jks-volume:/opt/app/jks
    ports:
      - "443:443"

volumes:
  jks-volume:
    driver: local
    driver_opts:
      type: none
      device: '/home/bot/luga-bot/jks'
      o: bind

