POST http://localhost:8082/api/v1/bot/sendMessage
Accept: application/json
Cache-Control: no-cache
Content-Type: application/json

{
  "test": "value",

    "message": {
      "message_id": "[INTEGER]",
      "from": {
        "id": "[INTEGER]",
        "is_bot": false,
        "first_name": "Name",
        "last_name": "LastName",
        "language_code": "ru"
      },
      "chat": {
        "id": "123",
        "first_name": "Name",
        "last_name": "LastName",
        "type": "private"
      },
      "date": "[INTEGER]",
      "text": "аау  ауа ка уа у sdddsd sdsd fdfdf dfd f df df f f ffrrfrfывывывыв ывывывыв аап апап ап ап апап ап п п"
    }

}

###