server:
  port: ${PORT:443}
  ssl:
    key-store-type: JKS
    key-store: ${KEYSTORE_PATH}
    key-store-password: ${KEYSTORE_PASSWORD}
    key-alias: ${KEY_ALIAS}
    enabled: true

spring:
  application:
    name: bot-base
  main:
    allow-bean-definition-overriding: true

logging:
  path: ./logs
  level:
    ru.asv.bot: WARN
    org.springframework: WARN

bot-base:
  weatherToken: ${WEATHER_TOKEN}

#management:
#  endpoint:
#    logfile:
#      external_file: ./logs/bmd_base.log
#  endpoints:
#    web:
#      exposure:
#        include: "*"