name: Luga Bot CI

on:
  release: 
    types: [published]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: 11

    - name: Build Jar
      run: |
        ./gradlew bootJar

    - name: Get version
      id: vars
      run: echo ::set-output name=docker_tag::$(echo ${GITHUB_REF} | cut -d'/' -f3)

    - name: Login to DockerHub Registry
      run: echo ${{ secrets.DOCKERHUB_PASSWORD }} | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin

    - name: Build the tagged Docker image
      run: docker build . --file Dockerfile --tag lugabot:${{ steps.vars.outputs.docker_tag }}

    - name: Latest tag
      run: docker tag lugabot:${{ steps.vars.outputs.docker_tag }} lugabot:latest

    - name: Push the tagged Docker image
      run: docker push lugabot:${{ steps.vars.outputs.docker_tag }}

      
